host: 0.0.0.0
datastore:
  # Example for Spanner
  kind: "spanner-engine"
  project: "my-project"
  instance: "my-instance"
  database: "my_database"
  # service_account_key_file: "my-service-account-key/service_accounts_credentials.json"
