host: 0.0.0.0
datastore:
  # Example for AlloyDB
  kind: "alloydb-postgres"
  project: "my-project"
  region: "my-region"
  cluster: "my-cluster"
  instance: "my-instance"
  database: "my_database"
  user: "my-user"
  password: "my-password"
