steps:
# If using subfolder from repo root to build, you need to specify the relative location for each stage
# Kaniko: dockerfile location and context dir
# General build step: dir: arg for step
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=Dockerfile
  - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/frontend-service
  - --cache=true
  - --cache-ttl=6h
# # Deploy container image to Cloud Run
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'retrieval-service', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/retrieval-service', '--region', 'us-central1']
